reseume_sending = dict(uz="↗️Botga o'tish.",en="↗️Switch to bot.", ru = "↗️Перейти на бот.")
send_contact=dict(uz="Kontaktizni yuboring." , en="send your contact", ru = "Отправить контакт")
back_to_main_menu=dict(uz="🔙Bosh menuga qaytish",en="🔙Back to Main Menu", ru = "🔙Вернуться в главное меню")
send_location=dict(uz="📍Geolokatsiya yuborish" , en="Send me your location", ru = "Отправить геолокацию")
my_locations=dict(uz="📍Mening geolokatsiyalarim",en="My Locations", ru = "Мои геолокации")
menu_text=dict(uz="🍴Menyu",en="🍴Menu", ru = "🍴Меню")
book_table=dict(uz="🪑Joy band qilish",en="🪑Book Table", ru = "🪑Забронировать стол")
settings_text=dict(uz="⚙ Sozlamalar",en="⚙ Settings", ru = "⚙ Настройки")
rate_me=dict(uz="🌟Bizga baho bering",en="🌟 Rate me", ru = "🌟 Оценить меня")
location_contact=dict(uz="📍Lokatsiya/👤Kontaktlar", en="📍Locations /👤Contacts", ru = "📍Локации/👤Контакты")
social_media=dict(uz="📲Ijtimoiy tarmoqlar",en="📲Our Social Media", ru = "📲Социальные сети")
back_button=dict(uz="🔙Orqaga",en="🔙Back", ru = "🔙Назад")
manual = dict(uz="🗂Qo'llanma",en="🗂Manual", ru = "🗂Руководство")
resume = dict(uz="📑Resume yuborish",en="📑Send resume", ru = "📑Отправить резюме")
go_delivery=dict(uz="Tog'ora - Buyurtma uchun",en="Тогора на заказ", ru = "Togora for order")
phone_delivery=dict(uz="📞Buyurtma qilish",en="📞Заказать", ru = "📞Delivery")
back_button_name=dict(uz="🔙Orqaga",en="🔙Back", ru = "🔙Назад")
change_language_text=dict(uz="Tilni o'zgartirish",en="Change Language", ru = "Изменить язык")
yes_word=dict(uz="✅Ha",en="✅Yes", ru = "✅Да")
no_word=dict(uz="❌Yo'q",en="❌No", ru = "❌Нет")
save_to_basket=dict(uz="📥Savatga qo'shish",en="📥Add to Basket", ru = "📥Добавить в корзину")
basket_button=dict(uz="📥Savat",en="📥Basket", ru = "📥Корзина")
booking_meal=dict(uz='🚖Buyurtma berish',en='🚖Order Meal', ru = '🚖Заказать еду')
clear_basket=dict(uz="🗑Savatni tozalash",en="🗑Clear Basket", ru = "🗑Очистить корзину")
time_delivery=dict(uz="🕒Yetkazib berish vaqti",en="🕒Delivery Time", ru = "🕒Время доставки")
cash_payment=dict(uz="💵Naqd pul",en="💵Cash Payment" , ru = "💵Наличные")
conformation=dict(uz="✅Tasdiqlash",en="✅Confirm" , ru = "✅Подтвердить")
cancel=dict(uz="❌Bekor qilish",en="❌Cancel" , ru = "❌Отменить")
def idea_report_text(data,lang):
    data_lang=dict(uz=f"Fikr-mulohazalar: \nServis Sifati:{data['servis']}\nTaom Sifati: {data['food_rate']}\nFikr-mulohaza: {data['user_idea']}\nUsername: @{data['user_name']}\nTelefon raqam: {data['phone_number']}" , en=f"Ideas: \nService Quality:{data['servis']}\nFood Quality: {data['food_rate']}\nIdea: {data['user_idea']}\nUsername: @{data['user_name']}\nPhone number: {data['phone_number']}", ru = f"Идеи: \nКачество обслуживания:{data['servis']}\nКачество еды: {data['food_rate']}\nИдея: {data['user_idea']}\nUsername: @{data['user_name']}\nНомер телефона: {data['phone_number']}")
    return data_lang[lang]
